name: Simulate a releasy thing

on:
  push:
    branches: [ "evil-branch" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: live
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        env: 
          super_secret: ${{ secrets.SUPER_SECRET_THING }}
          env_var: ${{ vars.LIVE_ENVIRONMENT_VARIABLE }}
        run: echo $super_secret $env_var
