name: CI

# Controls when the workflow will run
on:
  push:
  pull_request:
  merge_group:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Our builds are slow
        run: sleep 60
      - name: Our builds are flaky
        run: exit $(($RANDOM % 2))
