name: CI


on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Push a change to the branch
        run: |
          version=$(cat version.txt)
          echo $((version+1)) > version.txt
          echo "Written new version to file:"
          cat version.txt
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -am "Increment version"
          git push
